### ISSUE TITLE
Building library for Android

### ISSUE THREAD

**Issue by mdalzin** [BrunoMoureau/PocketSphinxXam#3]
Thank you so much this project, it's been extremely helpful. I'm currently trying to replicate the binding process with SWIG, and I was wondering how you were able to compile the libpocketsphinxwrap.so file for all Android architectures, as swig only generates one of them. Any help would be greatly appreciated, thanks!

**Comment by BrunoMoureau** [comment]
You are welcome :)
I will try to take a look at this soon. 
To be honest, it's been a year now and I can't remember how I did it.

**Comment by BrunoMoureau** [comment]
Good news ! I found back all the files I used to generate the C# wrapper, assets etc. 
I should be able to understand and reproduce what I did one year ago. I will try to take a look at it soon and add the files to this repo with detailed explanations.

**Comment by mdalzin** [comment]
Sounds great, thanks!

**Comment by BrunoMoureau** [comment]
I have added information about how I built it for Xamarin.Android. 
Tell me if you need help for something else or if you can't reproduce what I did.

**Comment by mdalzin** [comment]
Thank you so much! I'll get on trying to build this soon!
