### ISSUE TITLE
Integrating CMU Sphinx - Pocket Sphinx  into C# 

### ISSUE THREAD

**Issue by waleedmakarem** [BrunoMoureau/PocketSphinxXam#5]
Dear Sir, 
I am trying to use CMU Sphinx into C#, but without success.
Are you able to use CMU Sphinx or CMU PocketSphinx into C# ?
Kindly advise, as I am totally lost :).
Thanks.
Waleed

**Comment by BrunoMoureau** [comment]
Hi,

I am sorry to answer you only now but I hope you found what you need !
Unfortunately, I can't provide you more help than this repository... 

I really struggled to achieve this project and I published it more like as "hints" for people trying to achieve the same kind of work.
I no longer work on the project using CMU Sphinx and so this repository will not receive any update in the future.

Sorry again for the huge answer delay.

Bruno
